# Generated by Django 3.0.8 on 2020-07-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FourStepStatusMixin',
        ),
    ]
