# Generated by Django 3.0.8 on 2020-07-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FourStepStatusMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRS', 'Trash'), ('DRF', 'Draft'), ('VLD', 'Valid'), ('APP', 'Approved'), ('RJC', 'Rejected'), ('PRS', 'Processed'), ('CMP', 'Complete'), ('INV', 'Invoiced'), ('PND', 'Pending'), ('UNP', 'Un Paid'), ('PID', 'Paid'), ('CLS', 'Closed'), ('PST', 'Posted')], default='DRF', editable=False, max_length=6, verbose_name='Status')),
                ('date_trashed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date trashed')),
                ('date_drafted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date drafted')),
                ('date_validated', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date validated')),
                ('date_completed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date completed')),
                ('date_processed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date processed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
