# Generated by Django 3.0.8 on 2020-07-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='short_name',
        ),
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(default='Jhon Doe', max_length=30, verbose_name='full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='short_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='short name'),
        ),
    ]
