# Generated by Django 3.0.8 on 2020-07-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_auth', '0002_auto_20200722_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
