# Generated by Django 3.0.8 on 2020-07-21 08:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('hashed_url', models.CharField(editable=False, max_length=128, unique=True, verbose_name='Hashed url')),
                ('original_url', models.URLField(unique=True, verbose_name='Original Url')),
                ('ads', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('clicked', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Short Url',
                'verbose_name_plural': 'Short Urls',
            },
        ),
    ]
