# Generated by Django 3.0.8 on 2020-07-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.BooleanField(default=False, help_text='This invoice is based on customer contract'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Contract number'),
        ),
    ]
