# Generated by Django 3.0.8 on 2020-07-22 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nip', models.CharField(max_length=25)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sister_auth.Person')),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nama_kelas', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AKTIF', 'Aktif'), ('SELESAI', 'Selesai')], default='PENDING', max_length=10)),
                ('guru_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Guru')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='KompetensiInti',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nomor', models.IntegerField()),
                ('deskripsi', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'Kompetensi Inti',
                'verbose_name_plural': 'Kompetensi Inti',
            },
        ),
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kode', models.CharField(editable=False, max_length=25, unique=True)),
                ('nama', models.CharField(max_length=225)),
                ('tahun', models.IntegerField(default=0)),
                ('kkni', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('tingkat', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('revisi', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kurikulum',
                'verbose_name_plural': 'Kurikulum',
                'unique_together': {('tahun', 'kkni', 'tingkat', 'revisi')},
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kode', models.CharField(max_length=25)),
                ('nama', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='MataPelajaranKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kkm', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Kriteria ketuntansan minimal')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Kelas')),
            ],
            options={
                'verbose_name': 'Mata Pelajaran Kelas',
                'verbose_name_plural': 'Mata Pelajaran Kelas',
            },
        ),
        migrations.CreateModel(
            name='MataPelajaranKurikulum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Kurikulum')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.MataPelajaran')),
            ],
            options={
                'verbose_name': 'Mata Pelajaran Kurikulum',
                'verbose_name_plural': 'Mata Pelajaran Kurikulum',
            },
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('npsn', models.CharField(max_length=25)),
                ('nss', models.CharField(max_length=25)),
                ('nama_sekolah', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Sekolah',
                'verbose_name_plural': 'Sekolah',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nis', models.CharField(max_length=25, null=True)),
                ('nisn', models.CharField(max_length=25, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Aktif'), (2, 'Alumni'), (3, 'Drop Out'), (99, 'Lainnya')], default=1)),
                ('status_lain', models.CharField(blank=True, max_length=56, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sister_auth.Person')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kode', models.CharField(editable=False, max_length=10, unique=True)),
                ('tahun_mulai', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)])),
                ('tahun_akhir', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)])),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
            },
        ),
        migrations.CreateModel(
            name='Wali',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.IntegerField(choices=[(1, 'Ayah'), (2, 'Ibu'), (3, 'Paman'), (4, 'Bibi'), (5, 'Kakek'), (6, 'Nenek'), (99, 'Lainnya')], default=1)),
                ('status_lain', models.CharField(blank=True, max_length=56, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sister_auth.Person')),
            ],
            options={
                'verbose_name': 'Wali',
                'verbose_name_plural': 'Wali',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nomor', models.IntegerField()),
                ('judul', models.CharField(max_length=225)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('mata_pelajaran_kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.MataPelajaranKurikulum')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Tema',
            },
        ),
        migrations.CreateModel(
            name='SiswaKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.IntegerField(choices=[(1, 'Baru'), (2, 'Tinggal Kelas'), (99, 'Lainnya')], default=1)),
                ('status_lain', models.CharField(blank=True, max_length=56, null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Siswa')),
            ],
            options={
                'verbose_name': 'Siswa Kelas',
                'verbose_name_plural': 'Siswa Kelas',
                'unique_together': {('siswa', 'kelas')},
            },
        ),
        migrations.AddField(
            model_name='siswa',
            name='wali',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Wali'),
        ),
        migrations.CreateModel(
            name='RentangNilai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai_minimum', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nilai_maximum', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('predikat', models.CharField(choices=[('A', 'Sangat Baik'), ('B', 'Baik'), ('C', 'Cukup'), ('D', 'Buruk'), ('E', 'Sangat Buruk')], default='A', max_length=1)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Kelas')),
            ],
            options={
                'verbose_name': 'Rentang Nilai',
                'verbose_name_plural': 'Rentang Nilai',
            },
        ),
        migrations.CreateModel(
            name='PresensiSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Kelas')),
            ],
            options={
                'verbose_name': 'Presensi Siswa',
                'verbose_name_plural': 'Presensi Siswa',
            },
        ),
        migrations.CreateModel(
            name='PenilaianSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('mata_pelajaran_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.MataPelajaranKelas')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Penilaian Siswa',
                'verbose_name_plural': 'Penilaian Siswa',
                'unique_together': {('siswa_kelas', 'mata_pelajaran_kelas')},
            },
        ),
        migrations.CreateModel(
            name='NilaiSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('nilai', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kelas', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.MataPelajaranKurikulum')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.SiswaKelas')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.TahunAjaran')),
            ],
            options={
                'verbose_name': 'Nilai Siswa',
                'verbose_name_plural': 'Nilai Siswa',
            },
        ),
        migrations.AddField(
            model_name='matapelajarankelas',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.MataPelajaranKurikulum'),
        ),
        migrations.CreateModel(
            name='KompetensiDasar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nomor', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('ph', models.BooleanField(default=True)),
                ('pts', models.BooleanField(default=False)),
                ('pas', models.BooleanField(default=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('kompetensi_inti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.KompetensiInti')),
                ('mata_pelajaran_kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.MataPelajaranKurikulum')),
            ],
            options={
                'verbose_name': 'Kompetensi Dasar',
                'verbose_name_plural': 'Kompetensi Dasar',
                'unique_together': {('mata_pelajaran_kurikulum', 'kompetensi_inti', 'nomor')},
            },
        ),
        migrations.AddField(
            model_name='kelas',
            name='kurikulum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Kurikulum'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.TahunAjaran'),
        ),
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hari', models.IntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')], default=1)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.Kelas')),
            ],
            options={
                'verbose_name': 'Jadwal Pelajaran',
                'verbose_name_plural': 'Jadwal Pelajaran',
                'unique_together': {('hari', 'kelas')},
            },
        ),
        migrations.CreateModel(
            name='ItemJadwalPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('jam_mulai', models.TimeField(default=django.utils.timezone.now)),
                ('jam_berakhir', models.TimeField(default=django.utils.timezone.now)),
                ('deskripsi', models.CharField(blank=True, max_length=225, null=True)),
                ('jadwal_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sister_sekolah.JadwalPelajaran')),
                ('mata_pelajaran_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.MataPelajaranKelas')),
            ],
            options={
                'verbose_name': 'Jadwal Pelajaran',
                'verbose_name_plural': 'Jadwal Pelajaran',
            },
        ),
        migrations.AlterUniqueTogether(
            name='matapelajarankelas',
            unique_together={('kelas', 'mata_pelajaran')},
        ),
        migrations.CreateModel(
            name='ItemPresensiSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Tanpa Keterangan')], default='H', max_length=3)),
                ('presensi_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sister_sekolah.PresensiSiswa')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='sister_sekolah.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Item Presensi Siswa',
                'verbose_name_plural': 'Item Presensi Siswa',
                'unique_together': {('presensi_siswa', 'siswa_kelas')},
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('jenis_penilaian', models.CharField(choices=[('PH', 'Penilaian Harian'), ('PTS', 'Penilaian Tengah Semester'), ('PAS', 'Penilaian Akhir Semester')], default='PH', max_length=3)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sister_sekolah.KompetensiDasar')),
                ('penilaian_siswa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sister_sekolah.PenilaianSiswa')),
            ],
            options={
                'verbose_name': 'Item Penilaian Siswa',
                'verbose_name_plural': 'Item Penilaian Siswa',
                'ordering': ['jenis_penilaian', 'kompetensi_dasar__nomor'],
                'unique_together': {('penilaian_siswa', 'kompetensi_dasar', 'jenis_penilaian')},
            },
        ),
    ]
