# Generated by Django 3.0.8 on 2020-07-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentangnilai',
            name='aksi',
            field=models.CharField(choices=[('pertahankan', 'pertahankan'), ('tingkatkan', 'tingkatkan'), ('perlu bimbingan', 'perlu_bimbingan')], default='tingkatkan', max_length=125),
        ),
        migrations.AlterField(
            model_name='siswakelas',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to='sister_sekolah.Kelas'),
        ),
        migrations.AlterField(
            model_name='siswakelas',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='sister_sekolah.Siswa'),
        ),
        migrations.AlterUniqueTogether(
            name='presensisiswa',
            unique_together={('kelas', 'tanggal')},
        ),
    ]
