# Generated by Django 3.0.8 on 2020-07-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0002_auto_20200724_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompetensidasar',
            name='keyword',
            field=models.CharField(default='', max_length=255, verbose_name='Kata kunci'),
            preserve_default=False,
        ),
    ]
