# Generated by Django 3.0.8 on 2020-07-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0003_kompetensidasar_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetensidasar',
            name='deskripsi',
            field=models.TextField(verbose_name='Kata kunci'),
        ),
    ]
