# Generated by Django 3.0.8 on 2020-07-24 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0004_auto_20200724_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='EktraKurikuler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nama', models.CharField(max_length=225, verbose_name='nama')),
            ],
            options={
                'verbose_name': 'Ekstra Kurikuler',
                'verbose_name_plural': 'Ekstra Kurikuler',
            },
        ),
        migrations.CreateModel(
            name='PenilaianEkstraKurikuler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('nilai', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ekskul', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.EktraKurikuler')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.SiswaKelas')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.TahunAjaran')),
            ],
            options={
                'verbose_name': 'Nilai Ekstra Kurikuler',
                'verbose_name_plural': 'Nilai Ekstra Kurikuler',
            },
        ),
    ]
