# Generated by Django 3.0.8 on 2020-07-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0005_ektrakurikuler_penilaianekstrakurikuler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EktraKurikuler',
            new_name='EkstraKurikuler',
        ),
    ]
