# Generated by Django 3.0.8 on 2020-07-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0006_auto_20200724_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penilaianekstrakurikuler',
            options={'verbose_name': 'Penilaian Ekstra Kurikuler', 'verbose_name_plural': 'Penilaian Ekstra Kurikuler'},
        ),
        migrations.AlterField(
            model_name='rentangnilai',
            name='aksi',
            field=models.CharField(choices=[('pertahankan', 'Pertahankan'), ('tingkatkan', 'Tingkatkan'), ('perlu_bimbingan', 'Perlu Bimbingan')], default='tingkatkan', max_length=125),
        ),
        migrations.AlterField(
            model_name='rentangnilai',
            name='predikat',
            field=models.CharField(choices=[('A', 'Sangat Baik'), ('B', 'Baik'), ('C', 'Cukup baik'), ('D', 'Kurang baik'), ('E', 'Sangat kurang')], default='A', max_length=1),
        ),
    ]
