# Generated by Django 3.0.8 on 2020-07-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0007_auto_20200724_0417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPenilaianSiswa',
            new_name='ItemPenilaianMataPelajaran',
        ),
        migrations.RenameModel(
            old_name='PenilaianSiswa',
            new_name='PenilaianMataPelajaran',
        ),
        migrations.AlterModelOptions(
            name='penilaianmatapelajaran',
            options={'verbose_name': 'Penilaian Mata Pelajaran', 'verbose_name_plural': 'Penilaian Mata Pelajaran'},
        ),
        migrations.AlterField(
            model_name='penilaianekstrakurikuler',
            name='ekskul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.EkstraKurikuler'),
        ),
    ]
