# Generated by Django 3.0.8 on 2020-07-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0009_bobotpenilaian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobotpenilaian',
            name='mata_pelajaran_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_sekolah.MataPelajaranKelas'),
        ),
    ]
