# Generated by Django 3.0.8 on 2020-07-24 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0010_auto_20200724_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobotpenilaian',
            name='pas',
            field=models.PositiveIntegerField(default=0, help_text='Penilaian Akhir Semester', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bobotpenilaian',
            name='ph',
            field=models.PositiveIntegerField(default=0, help_text='Penilaian Harian', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bobotpenilaian',
            name='pts',
            field=models.PositiveIntegerField(default=0, help_text='Penilaian Tengah Semester', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bobotpenilaian',
            name='tugas',
            field=models.PositiveIntegerField(default=0, help_text='Tugas dan Pekerjaan Rumah', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='itempenilaianmatapelajaran',
            name='jenis_penilaian',
            field=models.CharField(choices=[('TGS', 'Tugas'), ('PH', 'Penilaian Harian'), ('PTS', 'Penilaian Tengah Semester'), ('PAS', 'Penilaian Akhir Semester')], default='PH', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='bobotpenilaian',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bobotpenilaian',
            name='bobot',
        ),
        migrations.RemoveField(
            model_name='bobotpenilaian',
            name='jenis_penilaian',
        ),
    ]
