# Generated by Django 3.0.8 on 2020-07-24 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0012_auto_20200724_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobotpenilaian',
            name='kkm',
            field=models.PositiveIntegerField(default=0, help_text='Kriteria Ketuntasan Minimal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
