# Generated by Django 3.0.8 on 2020-07-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0013_bobotpenilaian_kkm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matapelajarankelas',
            name='kkm',
        ),
    ]
