# Generated by Django 3.0.8 on 2020-07-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0014_remove_matapelajarankelas_kkm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobotpenilaian',
            name='mata_pelajaran_kelas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bobot', to='sister_sekolah.MataPelajaranKelas'),
        ),
    ]
