# Generated by Django 3.0.8 on 2020-07-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0015_auto_20200724_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='guru_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='sister_sekolah.Guru'),
        ),
    ]
