# Generated by Django 3.0.8 on 2020-07-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0016_auto_20200724_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajarankelas',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran', to='sister_sekolah.Guru'),
        ),
    ]
