# Generated by Django 3.0.8 on 2020-07-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0017_auto_20200724_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemjadwalpelajaran',
            name='mata_pelajaran_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='sister_sekolah.MataPelajaranKelas'),
        ),
    ]
