# Generated by Django 3.0.8 on 2020-07-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0018_auto_20200724_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajarankelas',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran', to='sister_sekolah.Kelas'),
        ),
        migrations.AlterField(
            model_name='rentangnilai',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentang_nilai', to='sister_sekolah.Kelas'),
        ),
    ]
