# Generated by Django 3.0.8 on 2020-07-24 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0019_auto_20200724_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiketKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hari', models.IntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')], default=1)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piket_kelas', to='sister_sekolah.Kelas')),
            ],
            options={
                'verbose_name': 'Piket Kelas',
                'verbose_name_plural': 'Presensi Siswa',
                'unique_together': {('kelas', 'hari')},
            },
        ),
        migrations.CreateModel(
            name='ItemPiketKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('piket_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sister_sekolah.PiketKelas')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piket_kelas', to='sister_sekolah.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Item PiketKelas',
                'verbose_name_plural': 'Item PiketKelas',
                'unique_together': {('piket_kelas', 'siswa_kelas')},
            },
        ),
    ]
