# Generated by Django 3.0.8 on 2020-07-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0020_itempiketkelas_piketkelas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piketkelas',
            options={'verbose_name': 'Piket Kelas', 'verbose_name_plural': 'Piket Kelas'},
        ),
    ]
