# Generated by Django 3.0.8 on 2020-07-24 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_ruang', '0001_initial'),
        ('sister_sekolah', '0021_auto_20200724_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='ruang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ruang', to='sister_ruang.Ruang'),
        ),
    ]
