# Generated by Django 3.0.8 on 2020-07-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_sekolah', '0022_kelas_ruang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalpelajaran',
            name='hari',
            field=models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=1),
        ),
    ]
