# Generated by Django 3.0.8 on 2020-07-17 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpellab_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_products.Product')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'permissions': (('lock_service', 'Can lock Service'), ('unlock_service', 'Can unlock Service'), ('export_service', 'Can export Service'), ('import_service', 'Can import Service')),
            },
            bases=('simpellab_products.product',),
        ),
        migrations.CreateModel(
            name='InspectionService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_services.Service')),
                ('parameter_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Inspection Service',
                'verbose_name_plural': 'Inspection Services',
            },
            bases=('simpellab_services.service',),
        ),
        migrations.CreateModel(
            name='LaboratoriumService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_services.Service')),
                ('parameter_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Laboratorium Service',
                'verbose_name_plural': 'Laboratorium Services',
            },
            bases=('simpellab_services.service',),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('ptype', models.CharField(choices=[('LAB', 'Laboratory'), ('LIT', 'Inspection')], default='Laboratory', max_length=3, verbose_name='Parameter type')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simpellab_products.UnitOfMeasure', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='LaboratoriumServiceParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_services', to='simpellab_services.Parameter', verbose_name='Parameter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_parameters', to='simpellab_services.LaboratoriumService', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Laboratorium Service Parameter',
                'verbose_name_plural': 'Laboratorium Service Parameters',
                'unique_together': {('service', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='InspectionServiceParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_services', to='simpellab_services.Parameter', verbose_name='Parameter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_parameters', to='simpellab_services.LaboratoriumService', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Inspection Service Parameter',
                'verbose_name_plural': 'Inspection Service Parameters',
                'unique_together': {('service', 'parameter')},
            },
        ),
    ]
