# Generated by Django 3.0.8 on 2020-07-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionserviceparameter',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_parameters', to='simpellab_services.InspectionService', verbose_name='Service'),
        ),
    ]
