# Generated by Django 3.0.8 on 2020-07-17 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_services', '0002_auto_20200717_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_services.Service')),
            ],
            options={
                'verbose_name': 'Calibration',
                'verbose_name_plural': 'Calibration',
            },
            bases=('simpellab_services.service',),
        ),
        migrations.CreateModel(
            name='ConsultancyService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_services.Service')),
            ],
            options={
                'verbose_name': 'Consultancy',
                'verbose_name_plural': 'Consultancies',
            },
            bases=('simpellab_services.service',),
        ),
        migrations.CreateModel(
            name='MiscService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_services.Service')),
            ],
            options={
                'verbose_name': 'Common Service',
                'verbose_name_plural': 'Common Services',
            },
            bases=('simpellab_services.service',),
        ),
        migrations.CreateModel(
            name='ResearchService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_services.Service')),
            ],
            options={
                'verbose_name': 'Research and Development',
                'verbose_name_plural': 'Research and Developments',
            },
            bases=('simpellab_services.service',),
        ),
        migrations.CreateModel(
            name='SertificationService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_services.Service')),
            ],
            options={
                'verbose_name': 'Product Sertification',
                'verbose_name_plural': 'Product Sertifications',
            },
            bases=('simpellab_services.service',),
        ),
        migrations.CreateModel(
            name='TrainingService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_services.Service')),
                ('min_audience', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Training and Coaching',
                'verbose_name_plural': 'Training and Coachings',
            },
            bases=('simpellab_services.service',),
        ),
        migrations.AlterModelOptions(
            name='inspectionservice',
            options={'verbose_name': 'Technical Inspection', 'verbose_name_plural': 'Technical Inspections'},
        ),
        migrations.AlterModelOptions(
            name='inspectionserviceparameter',
            options={'verbose_name': 'Inspection Parameter', 'verbose_name_plural': 'Inspection Parameters'},
        ),
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2048)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='simpellab_services.InspectionService', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Training Topic',
                'verbose_name_plural': 'Training Topics',
            },
        ),
    ]
