# Generated by Django 3.0.8 on 2020-07-17 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_services', '0003_auto_20200717_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtopic',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='simpellab_services.TrainingService', verbose_name='Service'),
        ),
    ]
