# Generated by Django 3.0.8 on 2020-07-17 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_services', '0004_auto_20200717_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='price',
        ),
        migrations.AlterField(
            model_name='trainingservice',
            name='min_audience',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum audience'),
        ),
    ]
