# Generated by Django 3.0.8 on 2020-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_services', '0005_auto_20200717_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingservice',
            old_name='min_audience',
            new_name='audience_min',
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='audience_criterias',
            field=models.TextField(default=1, max_length=2048, verbose_name='Audience criterias'),
            preserve_default=False,
        ),
    ]
