# Generated by Django 3.0.8 on 2020-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_services', '0006_auto_20200717_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='code'),
        ),
    ]
