# Generated by Django 3.0.8 on 2020-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_services', '0007_auto_20200717_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='price'),
        ),
    ]
