# Generated by Django 3.0.8 on 2020-07-21 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpellab_blueprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='name',
            field=models.CharField(help_text='Sample name or identifier', max_length=512, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
