# Generated by Django 3.0.8 on 2020-07-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpellab_sales', '0002_auto_20200718_0241'),
        ('simpellab_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SertificationOrder',
            fields=[
                ('salesorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.SalesOrder')),
            ],
            options={
                'verbose_name': 'Sertification Order',
                'verbose_name_plural': 'Sertification Orders',
            },
            bases=('simpellab_sales.salesorder',),
        ),
        migrations.CreateModel(
            name='SertificationService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_products.Service')),
            ],
            options={
                'verbose_name': 'Product Sertification',
                'verbose_name_plural': 'Product Sertifications',
            },
            bases=('simpellab_products.service',),
        ),
        migrations.CreateModel(
            name='SertificationOrderItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.OrderItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='simpellab_sales_sertification.SertificationOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='simpellab_sales_sertification.SertificationService')),
            ],
            options={
                'verbose_name': 'Sertification Order Item',
                'verbose_name_plural': 'Sertification Order Items',
                'unique_together': {('order', 'product')},
            },
            bases=('simpellab_sales.orderitem',),
        ),
    ]
