# Generated by Django 3.0.8 on 2020-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_partners', '0002_auto_20200717_0104'),
        ('simpellab_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_supplier': True}, related_name='products', to='simpellab_partners.Partner', verbose_name='Suppliers'),
        ),
    ]
