# Generated by Django 3.0.8 on 2020-07-20 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpellab_products', '0001_initial'),
        ('simpellab_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoriumOrder',
            fields=[
                ('salesorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.SalesOrder')),
            ],
            options={
                'verbose_name': 'Laboratorium Order',
                'verbose_name_plural': 'Laboratorium Orders',
            },
            bases=('simpellab_sales.salesorder',),
        ),
        migrations.CreateModel(
            name='LaboratoriumService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_products.Service')),
            ],
            options={
                'verbose_name': 'Laboratorium Test',
                'verbose_name_plural': 'Laboratorium Tests',
            },
            bases=('simpellab_products.service',),
        ),
        migrations.CreateModel(
            name='LaboratoriumOrderItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.OrderItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='simpellab_sales_laboratorium.LaboratoriumOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='simpellab_sales_laboratorium.LaboratoriumService')),
            ],
            options={
                'verbose_name': 'Laboratorium Order Item',
                'verbose_name_plural': 'Laboratorium Order Items',
            },
            bases=('simpellab_sales.orderitem',),
        ),
        migrations.CreateModel(
            name='LaboratoriumOrderItemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Note')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simpellab_sales_laboratorium.LaboratoriumOrderItem', verbose_name='Product')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_parameters', to='simpellab_products.Parameter', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'unique_together': {('order_item', 'parameter')},
            },
        ),
    ]
