# Generated by Django 3.0.8 on 2020-07-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_laboratorium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoriumservice',
            options={'verbose_name': 'Laboratorium Test', 'verbose_name_plural': 'Laboratorium Tests'},
        ),
        migrations.AlterModelOptions(
            name='laboratoriumserviceparameter',
            options={'verbose_name': 'Laboratorium Parameter', 'verbose_name_plural': 'Laboratorium Parameters'},
        ),
    ]
