# Generated by Django 3.0.8 on 2020-07-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_laboratorium', '0002_auto_20200718_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoriumserviceparameter',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simpellab_sales_laboratorium.LaboratoriumService', verbose_name='Service'),
        ),
    ]
