# Generated by Django 3.0.8 on 2020-07-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_laboratorium', '0003_auto_20200718_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoriumorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='simpellab_sales_laboratorium.LaboratoriumService'),
        ),
    ]
