# Generated by Django 3.0.8 on 2020-07-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_laboratorium', '0004_auto_20200718_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoriumservice',
            name='parameter_price',
        ),
        migrations.DeleteModel(
            name='LaboratoriumServiceParameter',
        ),
    ]
