# Generated by Django 3.0.8 on 2020-07-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_products', '0001_initial'),
        ('simpellab_sales_laboratorium', '0005_auto_20200718_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaboratoriumOrderItemExtraParameter',
            new_name='LaboratoriumOrderItemParameter',
        ),
    ]
