# Generated by Django 3.0.8 on 2020-07-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_laboratorium', '0006_auto_20200718_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoriumorderitemparameter',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simpellab_sales_laboratorium.LaboratoriumOrderItem', verbose_name='Product'),
        ),
    ]
