# Generated by Django 3.0.8 on 2020-07-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_products', '0001_initial'),
        ('simpellab_sales_laboratorium', '0007_auto_20200718_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoriumorderitemparameter',
            options={'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterField(
            model_name='laboratoriumorderitemparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_parameters', to='simpellab_products.Parameter', verbose_name='Parameter'),
        ),
    ]
