# Generated by Django 3.0.8 on 2020-07-18 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpellab_sales', '0002_auto_20200718_0241'),
        ('simpellab_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionOrder',
            fields=[
                ('salesorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.SalesOrder')),
            ],
            options={
                'verbose_name': 'Inspection Order',
                'verbose_name_plural': 'Inspection Orders',
            },
            bases=('simpellab_sales.salesorder',),
        ),
        migrations.CreateModel(
            name='InspectionService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_products.Service')),
                ('parameter_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Technical Inspection',
                'verbose_name_plural': 'Technical Inspections',
            },
            bases=('simpellab_products.service',),
        ),
        migrations.CreateModel(
            name='InspectionOrderItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.OrderItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='simpellab_sales_inspection.InspectionOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='simpellab_sales_inspection.InspectionService')),
            ],
            options={
                'verbose_name': 'Inspection Order Item',
                'verbose_name_plural': 'Inspection Order Items',
                'unique_together': {('order', 'product')},
            },
            bases=('simpellab_sales.orderitem',),
        ),
        migrations.CreateModel(
            name='InspectionServiceParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_services', to='simpellab_products.Parameter', verbose_name='Parameter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_parameters', to='simpellab_sales_inspection.InspectionService', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Inspection Parameter',
                'verbose_name_plural': 'Inspection Parameters',
                'unique_together': {('service', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='InspectionOrderItemExtraParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_parameters', to='simpellab_sales_inspection.InspectionOrderItem', verbose_name='Product')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_extra_parameters', to='simpellab_products.Parameter', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Extra Parameter',
                'verbose_name_plural': 'Extra Parameters',
                'unique_together': {('order_item', 'parameter')},
            },
        ),
    ]
