# Generated by Django 3.0.8 on 2020-07-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_inspection', '0002_auto_20200718_1007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inspectionorderitem',
            unique_together=set(),
        ),
    ]
