# Generated by Django 3.0.8 on 2020-07-19 04:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_products', '0001_initial'),
        ('simpellab_sales_inspection', '0004_auto_20200718_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionOrderItemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simpellab_sales_inspection.InspectionOrderItem', verbose_name='Product')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_parameters', to='simpellab_products.Parameter', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'unique_together': {('order_item', 'parameter')},
            },
        ),
        migrations.RemoveField(
            model_name='inspectionserviceparameter',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='inspectionserviceparameter',
            name='service',
        ),
        migrations.DeleteModel(
            name='InspectionOrderItemExtraParameter',
        ),
        migrations.DeleteModel(
            name='InspectionServiceParameter',
        ),
    ]
