# Generated by Django 3.0.8 on 2020-07-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_inspection', '0005_auto_20200718_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionservice',
            name='parameter_price',
        ),
    ]
