# Generated by Django 3.0.8 on 2020-07-22 06:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_carts', '0006_auto_20200721_2356'),
        ('simpellab_products', '0001_initial'),
        ('simpellab_sales_inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCart',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_carts.Cart')),
                ('name', models.CharField(help_text='Sample name or identifier', max_length=512, verbose_name='Name')),
                ('note', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Note')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_carts', to='simpellab_sales_inspection.InspectionService', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inspection Cart',
                'verbose_name_plural': 'Inspection Carts',
            },
            bases=('simpellab_carts.cart',),
        ),
        migrations.CreateModel(
            name='InspectionCartParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Note')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simpellab_sales_inspection.InspectionCart', verbose_name='Cart')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_carts', to='simpellab_products.Parameter')),
            ],
            options={
                'verbose_name': 'Inspection Cart Parameter',
                'verbose_name_plural': 'Inspection Cart Parameters',
                'unique_together': {('cart', 'parameter')},
            },
        ),
    ]
