# Generated by Django 3.0.8 on 2020-07-22 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_blueprints', '0003_auto_20200721_2356'),
        ('simpellab_products', '0001_initial'),
        ('simpellab_sales_inspection', '0002_inspectioncart_inspectioncartparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionBlueprint',
            fields=[
                ('blueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_blueprints.Blueprint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='simpellab_sales_inspection.InspectionService')),
            ],
            options={
                'verbose_name': 'Inspection Blueprint',
                'verbose_name_plural': 'Inspection Blueprints',
            },
            bases=('simpellab_blueprints.blueprint',),
        ),
        migrations.CreateModel(
            name='InspectionBlueprintParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Note')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simpellab_sales_inspection.InspectionBlueprint', verbose_name='Blueprint')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lit_blueprints', to='simpellab_products.Parameter')),
            ],
            options={
                'verbose_name': 'Blueprint Parameter',
                'verbose_name_plural': 'Blueprint Parameters',
                'unique_together': {('blueprint', 'parameter')},
            },
        ),
    ]
