# Generated by Django 3.0.8 on 2020-07-18 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, help_text='Contract end', verbose_name='Date end'),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now, help_text='Contract cretaed', verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Contract start', verbose_name='Date start'),
        ),
    ]
