# Generated by Django 3.0.8 on 2020-07-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_contracts', '0002_auto_20200718_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='date_start',
            new_name='active_at',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_end',
            new_name='expired_at',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_issued',
            new_name='issued_at',
        ),
    ]
