# Generated by Django 3.0.8 on 2020-07-26 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
        ('sister_kurikulum', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('nilai', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_sister_penilaian.penilaian_set+', to='contenttypes.ContentType')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_pembelajaran.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Penilaian',
                'verbose_name_plural': 'Penilaian',
            },
        ),
        migrations.CreateModel(
            name='BobotPenilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tugas', models.PositiveIntegerField(default=10, help_text='Tugas dan Pekerjaan Rumah', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ph', models.PositiveIntegerField(default=20, help_text='Penilaian Harian', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pts', models.PositiveIntegerField(default=30, help_text='Penilaian Tengah Semester', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pas', models.PositiveIntegerField(default=40, help_text='Penilaian Akhir Semester', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('kkm', models.PositiveIntegerField(default=0, help_text='Kriteria Ketuntasan Minimal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('mata_pelajaran_kelas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bobot', to='sister_pembelajaran.MataPelajaranKelas')),
            ],
            options={
                'verbose_name': 'Bobot Penilaian',
                'verbose_name_plural': 'Bobot Penilaian',
            },
        ),
        migrations.CreateModel(
            name='PenilaianPembelajaran',
            fields=[
                ('penilaian_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sister_penilaian.Penilaian')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='sister_pembelajaran.MataPelajaranKelas')),
            ],
            options={
                'verbose_name': 'Penilaian Pembelajaran',
                'verbose_name_plural': 'Penilaian Pembelajaran',
            },
            bases=('sister_penilaian.penilaian',),
        ),
        migrations.CreateModel(
            name='PenilaianEkstraKurikuler',
            fields=[
                ('penilaian_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sister_penilaian.Penilaian')),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='sister_kurikulum.EkstraKurikuler')),
            ],
            options={
                'verbose_name': 'Penilaian Ekstra Kurikuler',
                'verbose_name_plural': 'Penilaian Ekstra Kurikuler',
            },
            bases=('sister_penilaian.penilaian',),
        ),
        migrations.CreateModel(
            name='ItemPenilaianTugas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tugas', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Tugas',
                'verbose_name_plural': 'Penilaian Tugas',
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianTengahSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tengah_semester', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tengah_semester', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Tengah Semester',
                'verbose_name_plural': 'Penilaian Tengah Semester',
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianHarian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harian', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harian', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Harian',
                'verbose_name_plural': 'Penilaian Harian',
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianAkhirSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='akhir_semester', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akhir_semester', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Akhir Semester',
                'verbose_name_plural': 'Penilaian Akhir Semester',
            },
        ),
    ]
