# Generated by Django 3.0.8 on 2020-07-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpellab_sales', '0001_initial'),
        ('simpellab_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchOrder',
            fields=[
                ('salesorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.SalesOrder')),
            ],
            options={
                'verbose_name': 'Research Order',
                'verbose_name_plural': 'Research Orders',
            },
            bases=('simpellab_sales.salesorder',),
        ),
        migrations.CreateModel(
            name='ResearchService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_products.Service')),
            ],
            options={
                'verbose_name': 'Research and Development',
                'verbose_name_plural': 'Research and Developments',
            },
            bases=('simpellab_products.service',),
        ),
        migrations.CreateModel(
            name='ResearchOrderItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.OrderItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='simpellab_sales_research.ResearchOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='simpellab_sales_research.ResearchService')),
            ],
            options={
                'verbose_name': 'Research Order Item',
                'verbose_name_plural': 'Research Order Items',
            },
            bases=('simpellab_sales.orderitem',),
        ),
    ]
