# Generated by Django 3.0.8 on 2020-07-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_research', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='researchorderitem',
            unique_together=set(),
        ),
    ]
