# Generated by Django 3.0.8 on 2020-07-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_todo', '0002_order_orderitem_orderitemfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemfee',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpellab_todo.OrderItem'),
        ),
    ]
