# Generated by Django 3.0.8 on 2020-07-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_todo', '0003_auto_20200716_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemfee',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderitemfee',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
