# Generated by Django 3.0.8 on 2020-07-17 06:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personaddress',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='privacy',
        ),
        migrations.AddField(
            model_name='personaddress',
            name='privacy',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy'),
        ),
        migrations.AddField(
            model_name='personcontact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='personcontact',
            name='modified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personcontact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
