# Generated by Django 3.0.8 on 2020-07-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwalkelas',
            options={'verbose_name': 'Jadwal Kelas', 'verbose_name_plural': 'Jadwal Kelas'},
        ),
    ]
