# Generated by Django 3.0.8 on 2020-07-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpellab_products', '0001_initial'),
        ('simpellab_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscOrder',
            fields=[
                ('salesorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.SalesOrder')),
            ],
            options={
                'verbose_name': 'Misc Order',
                'verbose_name_plural': 'Misc Orders',
            },
            bases=('simpellab_sales.salesorder',),
        ),
        migrations.CreateModel(
            name='MiscService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_products.Service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
            bases=('simpellab_products.service',),
        ),
        migrations.CreateModel(
            name='MiscOrderItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_sales.OrderItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='simpellab_sales_misc.MiscOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='simpellab_sales_misc.MiscService')),
            ],
            options={
                'verbose_name': 'Misc Order Item',
                'verbose_name_plural': 'Misc Order Items',
            },
            bases=('simpellab_sales.orderitem',),
        ),
    ]
