# Generated by Django 3.0.8 on 2020-07-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscservice',
            options={'verbose_name': 'Misc Service', 'verbose_name_plural': 'Misc Services'},
        ),
    ]
