# Generated by Django 3.0.8 on 2020-07-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales_misc', '0002_auto_20200718_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='simpellab_sales_misc.MiscService'),
        ),
    ]
