# Generated by Django 3.0.8 on 2020-07-17 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='is_vendor',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='partnercontact',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
