# Generated by Django 3.0.8 on 2020-07-20 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance'),
        ),
        migrations.CreateModel(
            name='BalanceMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('flow', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3, verbose_name='Cash flow')),
                ('reference', models.CharField(max_length=125, verbose_name='reference')),
                ('note', models.TextField(blank=True, max_length=225, null=True, verbose_name='Note')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Amount')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpellab_partners.Partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Partner Balance Mutations',
            },
        ),
    ]
