# Generated by Django 3.0.8 on 2020-07-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_partners', '0003_auto_20200720_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancemutation',
            options={'verbose_name': 'Balance Mutations'},
        ),
    ]
