# Generated by Django 3.0.8 on 2020-07-21 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_carts', '0004_auto_20200721_1359'),
        ('simpellab_products', '0001_initial'),
        ('simpellab_sales_laboratorium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoriumCart',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_carts.Cart')),
                ('name', models.CharField(help_text='Sample name or identifier', max_length=512, verbose_name='Title')),
                ('note', models.CharField(max_length=2048, verbose_name='Note')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_carts', to='simpellab_sales_laboratorium.LaboratoriumService', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Laboratorium Cart',
                'verbose_name_plural': 'Laboratorium Carts',
            },
            bases=('simpellab_carts.cart',),
        ),
        migrations.CreateModel(
            name='LaboratoriumCartParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Note')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simpellab_sales_laboratorium.LaboratoriumCart', verbose_name='Cart')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_carts', to='simpellab_products.Parameter')),
            ],
            options={
                'verbose_name': 'Laboratorium Cart Parameter',
                'verbose_name_plural': 'Laboratorium Cart Parameters',
                'unique_together': {('cart', 'parameter')},
            },
        ),
    ]
