# Generated by Django 3.0.8 on 2020-07-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_carts', '0005_auto_20200721_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
    ]
