# Generated by Django 3.0.8 on 2020-07-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0002_auto_20200722_0423'),
        ('simpellab_carts', '0006_auto_20200721_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('simpellab_sales.salesorder',),
        ),
    ]
