# Generated by Django 3.0.8 on 2020-07-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('created_at',), 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
