# Generated by Django 3.0.8 on 2020-07-17 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0002_auto_20200717_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionorderitemextraparameter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='laboratoriumorderitemextraparameter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
