# Generated by Django 3.0.8 on 2020-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0002_auto_20200718_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='contract',
            field=models.BooleanField(default=False, help_text='This order is based on customer contract'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contract_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Contract number'),
        ),
    ]
