# Generated by Django 3.0.8 on 2020-07-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0003_auto_20200718_0314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonorderitem',
            unique_together=set(),
        ),
    ]
