# Generated by Django 3.0.8 on 2020-07-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_partners', '0002_auto_20200717_0104'),
        ('simpellab_sales', '0003_auto_20200717_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billed_to',
            field=models.ForeignKey(limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='simpellab_partners.Partner', verbose_name='Customer'),
        ),
    ]
