# Generated by Django 3.0.8 on 2020-07-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0003_auto_20200720_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='final_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='transfer_fee',
        ),
    ]
