# Generated by Django 3.0.8 on 2020-07-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0004_auto_20200718_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=512, null=True, verbose_name='Name'),
        ),
    ]
