# Generated by Django 3.0.8 on 2020-07-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0004_calibrationorder_calibrationorderitem_consultancyorder_consultancyorderitem_researchorder_researchor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laboratoriumorderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='laboratoriumorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='laboratoriumorderitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='laboratoriumorderitemextraparameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='laboratoriumorderitemextraparameter',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='laboratoriumorderitemextraparameter',
            name='parameter',
        ),
        migrations.DeleteModel(
            name='LaboratoriumOrder',
        ),
        migrations.DeleteModel(
            name='LaboratoriumOrderItem',
        ),
        migrations.DeleteModel(
            name='LaboratoriumOrderItemExtraParameter',
        ),
    ]
