# Generated by Django 3.0.8 on 2020-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0004_auto_20200720_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='date_approved',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date approved'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='date_rejected',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date rejected'),
        ),
    ]
