# Generated by Django 3.0.8 on 2020-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0004_invoice_billed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
    ]
