# Generated by Django 3.0.8 on 2020-07-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0005_auto_20200717_0537'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inspectionorderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inspectionorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='inspectionorderitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='inspectionorderitemextraparameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inspectionorderitemextraparameter',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='inspectionorderitemextraparameter',
            name='parameter',
        ),
        migrations.DeleteModel(
            name='InspectionOrder',
        ),
        migrations.DeleteModel(
            name='InspectionOrderItem',
        ),
        migrations.DeleteModel(
            name='InspectionOrderItemExtraParameter',
        ),
    ]
