# Generated by Django 3.0.8 on 2020-07-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0005_auto_20200720_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='qrcode',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qrcode'),
        ),
    ]
