# Generated by Django 3.0.8 on 2020-07-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0006_auto_20200717_0545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calibrationorderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='calibrationorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='calibrationorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='CalibrationOrder',
        ),
        migrations.DeleteModel(
            name='CalibrationOrderItem',
        ),
    ]
