# Generated by Django 3.0.8 on 2020-07-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0007_auto_20200717_0551'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultancyorderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='consultancyorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='consultancyorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ConsultancyOrder',
        ),
        migrations.DeleteModel(
            name='ConsultancyOrderItem',
        ),
    ]
