# Generated by Django 3.0.8 on 2020-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0007_auto_20200720_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='refund'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='refundable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='refundable'),
        ),
    ]
