# Generated by Django 3.0.8 on 2020-07-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0008_auto_20200720_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='refunded',
            new_name='refund',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='refundable',
        ),
    ]
