# Generated by Django 3.0.8 on 2020-07-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0008_auto_20200717_0557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='researchorderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='researchorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='researchorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ResearchOrder',
        ),
        migrations.DeleteModel(
            name='ResearchOrderItem',
        ),
    ]
