# Generated by Django 3.0.8 on 2020-07-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_sales', '0009_auto_20200720_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_closed',
        ),
    ]
