# Generated by Django 3.0.8 on 2020-07-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_products', '0001_initial'),
        ('simpellab_carts', '0003_auto_20200721_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='commoncart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_carts', to='simpellab_products.Product', verbose_name='Product'),
        ),
    ]
