# Generated by Django 3.0.8 on 2020-07-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_ruang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruang',
            options={'verbose_name': 'Ruang', 'verbose_name_plural': 'Ruang'},
        ),
        migrations.AddField(
            model_name='ruang',
            name='fungsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruang',
            name='kode',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ruang',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
