# Generated by Django 3.0.8 on 2020-07-21 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('simpellab_partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for confirmation'), ('preauth', 'Pre-authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], default='waiting', max_length=15, verbose_name='Status')),
                ('ptype', models.CharField(blank=True, choices=[('DP', 'Down Payment'), ('RP', 'Repayment')], default=None, help_text='Determine Down Payment or Repayment', max_length=2, null=True, verbose_name='Payment Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount')),
                ('memo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Memo')),
                ('date_confirmed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date confirmed')),
                ('date_rejected', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date rejected')),
                ('date_refunded', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date refunded')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simpellab_partners.Partner')),
            ],
            options={
                'verbose_name': 'Cash Flow',
                'verbose_name_plural': 'Cash Flows',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('rate_method', models.CharField(choices=[('PERCENT', 'Percentage'), ('NOMINAL', 'Nominal')], default='PERCENT', max_length=128, verbose_name='Rate method')),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transfer fee')),
                ('auto_confirm', models.BooleanField(default=False, help_text='Customer should inform payment manual if false', verbose_name='Auto confirmation')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_simpellab_payments.paymentmethod_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Method',
                'verbose_name_plural': 'Methods',
            },
        ),
        migrations.CreateModel(
            name='CashPaymentMethod',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_payments.PaymentMethod')),
            ],
            options={
                'verbose_name': 'Cash Payment',
                'verbose_name_plural': 'Cash Payment',
            },
            bases=('simpellab_payments.paymentmethod',),
        ),
        migrations.CreateModel(
            name='ManualTransferMethod',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_payments.PaymentMethod')),
                ('bank_name', models.CharField(max_length=128, verbose_name='Bank Name')),
                ('bank_branch_office', models.CharField(max_length=128, verbose_name='Branch Office')),
                ('bank_account', models.CharField(max_length=128, verbose_name='Account number')),
                ('bank_holder_name', models.CharField(max_length=128, verbose_name='Account holder')),
            ],
            options={
                'verbose_name': 'Manual Transfer',
                'verbose_name_plural': 'Manual Transfers',
            },
            bases=('simpellab_payments.paymentmethod',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('cashflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_payments.CashFlow')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
            bases=('simpellab_payments.cashflow',),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('cashflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_payments.CashFlow')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
            bases=('simpellab_payments.cashflow',),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('cashflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_payments.CashFlow')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
            bases=('simpellab_payments.cashflow',),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simpellab_payments.PaymentMethod', verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_simpellab_payments.cashflow_set+', to='contenttypes.ContentType'),
        ),
    ]
