# Generated by Django 3.0.8 on 2020-07-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('simpellab_payments', '0002_receipt_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashOnDelivery',
            new_name='CashPaymentMethod',
        ),
        migrations.AlterModelOptions(
            name='cashpaymentmethod',
            options={'verbose_name': 'Cash Payment', 'verbose_name_plural': 'Cash Payment'},
        ),
    ]
