# Generated by Django 3.0.8 on 2020-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_payments', '0003_auto_20200720_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='ptype',
            field=models.CharField(blank=True, choices=[('DP', 'Down Payment'), ('RP', 'Repayment')], default=None, max_length=2, null=True, verbose_name='Determine Down Payment or Repayment'),
        ),
    ]
