# Generated by Django 3.0.8 on 2020-07-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_payments', '0004_cashflow_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date confirmed'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='date_refunded',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date refunded'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='date_rejected',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date rejected'),
        ),
    ]
