# Generated by Django 3.0.8 on 2020-07-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpellab_payments', '0006_auto_20200720_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('cashflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simpellab_payments.CashFlow')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
            bases=('simpellab_payments.cashflow',),
        ),
    ]
